spring:
  datasource:
    url: "jdbc:h2:file:./tpo04-books/H2Database/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false"
    driver-class-name: "org.h2.Driver"
    username:
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl