DROP TABLE IF EXISTS Link;

CREATE TABLE Link
(
    Link_ID VARCHAR(10) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Target_Url VARCHAR(250) NOT NULL,
    Password VARCHAR(100) NULL,
    Visits BIGINT NOT NULL
);