INSERT INTO "User" (Email) VALUES ('alice@example.com');
INSERT INTO "User" (Email) VALUES ('bob@example.com');
INSERT INTO "User" (Email) VALUES ('charlie@example.com');
INSERT INTO "User" (Email) VALUES ('david@example.com');
INSERT INTO "User" (Email) VALUES ('eve@example.com');
INSERT INTO "User" (Email) VALUES ('frank@example.com');
INSERT INTO "User" (Email) VALUES ('grace@example.com');
INSERT INTO "User" (Email) VALUES ('heidi@example.com');
INSERT INTO "User" (Email) VALUES ('ivan@example.com');
INSERT INTO "User" (Email) VALUES ('judy@example.com');
INSERT INTO "User" (Email) VALUES ('mallory@example.com');
INSERT INTO "User" (Email) VALUES ('oscar@example.com');
INSERT INTO "User" (Email) VALUES ('peggy@example.com');
INSERT INTO "User" (Email) VALUES ('trent@example.com');
INSERT INTO "User" (Email) VALUES ('victor@example.com');
INSERT INTO "User" (Email) VALUES ('walter@example.com');
INSERT INTO "User" (Email) VALUES ('sybil@example.com');
INSERT INTO "User" (Email) VALUES ('carl@example.com');
INSERT INTO "User" (Email) VALUES ('doris@example.com');
INSERT INTO "User" (Email) VALUES ('edward@example.com');

INSERT INTO Role (Name) VALUES ('ADMIN');
INSERT INTO Role (Name) VALUES ('EDITOR');
INSERT INTO Role (Name) VALUES ('WRITER');
INSERT INTO Role (Name) VALUES ('READER');
INSERT INTO Role (Name) VALUES ('GUEST');
INSERT INTO Role (Name) VALUES ('MODERATOR');
INSERT INTO Role (Name) VALUES ('CONTRIBUTOR');
INSERT INTO Role (Name) VALUES ('MANAGER');
INSERT INTO Role (Name) VALUES ('ANALYST');
INSERT INTO Role (Name) VALUES ('SUPERVISOR');
INSERT INTO Role (Name) VALUES ('COORDINATOR');
INSERT INTO Role (Name) VALUES ('AUTHOR');
INSERT INTO Role (Name) VALUES ('BLOGGER');
INSERT INTO Role (Name) VALUES ('USER');
INSERT INTO Role (Name) VALUES ('MEMBER');
INSERT INTO Role (Name) VALUES ('VIP');
INSERT INTO Role (Name) VALUES ('SUBSCRIBER');
INSERT INTO Role (Name) VALUES ('PARTNER');
INSERT INTO Role (Name) VALUES ('AFFILIATE');
INSERT INTO Role (Name) VALUES ('STAFF');

INSERT INTO User_Role (User_ID, Role_ID) VALUES (1, 1);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (1, 4);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (2, 2);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (3, 3);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (4, 2);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (5, 5);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (6, 6);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (7, 7);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (8, 8);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (9, 9);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (10, 10);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (11, 11);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (12, 12);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (13, 13);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (14, 14);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (15, 15);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (16, 16);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (17, 17);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (18, 18);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (19, 19);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (20, 20);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (2, 1);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (3, 4);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (4, 3);
INSERT INTO User_Role (User_ID, Role_ID) VALUES (5, 6);

INSERT INTO Blog (Name, Manager_ID) VALUES ('Tech Insights', 1);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Daily News', 2);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Travel Diaries', 3);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Food Lovers', 4);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Health Tips', 5);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Finance Guru', 6);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Lifestyle Hub', 7);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Gaming Zone', 8);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Sports Arena', 9);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Movie Reviews', 10);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Music World', 11);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Education Corner', 12);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Science Today', 13);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Art and Culture', 14);
INSERT INTO Blog (Name, Manager_ID) VALUES ('History Channel', 15);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Book Club', 16);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Automotive Trends', 17);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Fashion Forward', 18);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Real Estate', 19);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Parenting Tips', 20);
INSERT INTO Blog (Name, Manager_ID) VALUES ('Independent Blog', NULL);

INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('AI Revolution', 1, 1);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Space Exploration', 2, 2);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Healthy Living', 3, 3);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('World Travel', 4, 4);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Culinary Secrets', 5, 5);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Market Trends', 6, 6);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Lifestyle Hacks', 7, 7);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('E-sports Rising', 8, 8);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Championship Highlights', 9, 9);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Blockbuster Movies', 10, 10);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('New Music Releases', 11, 11);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Educational Reform', 12, 12);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Scientific Breakthroughs', 13, 13);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Modern Art Trends', 14, 14);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Ancient History', 15, 15);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Literary Analysis', 16, 16);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Car Innovations', 17, 17);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Fashion Week', 18, 18);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Property Market', 19, 19);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Parenting Challenges', 20, 20);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Orphan Article', NULL, 1);
INSERT INTO Article (Title, Author_ID, Blog_ID) VALUES ('Detached Article', 2, NULL);