DROP TABLE IF EXISTS Article;
DROP TABLE IF EXISTS User_Role;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Blog;
DROP TABLE IF EXISTS "User";

CREATE TABLE "User"
(
    User_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Email   VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Role
(
    Role_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name    VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE User_Role
(
    User_ID BIGINT NOT NULL,
    Role_ID BIGINT NOT NULL,
    PRIMARY KEY (User_ID, Role_ID),
    FOREIGN KEY (User_ID) REFERENCES "User" (User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Role_ID) REFERENCES Role (Role_ID) ON DELETE CASCADE
);

CREATE TABLE Blog
(
    Blog_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name       VARCHAR(255) NOT NULL UNIQUE,
    Manager_ID BIGINT,
    FOREIGN KEY (Manager_ID) REFERENCES "User" (User_ID)
);

CREATE TABLE Article
(
    Article_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title     VARCHAR(255) NOT NULL,
    Author_ID BIGINT,
    Blog_ID   BIGINT,
    FOREIGN KEY (Author_ID) REFERENCES "User" (User_ID) ON DELETE SET NULL,
    FOREIGN KEY (Blog_ID) REFERENCES Blog (Blog_ID) ON DELETE SET NULL
);